### ISSUE TITLE
HungerGames - ERROR

### ISSUE THREAD

**Issue by ghost** [xBeastMode/AntiSpammer#12]
There is an error in HungerGames. Sorry for that I am writing there but there are not issues on HungerGames.

[Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'HungerGames vBuild#16': Class hungergames\lib\utils\Loader not found on hungergames\EventListener
[20:34:10] [Server thread/CRITICAL]: ClassNotFoundException: "Class hungergames\lib\utils\Loader not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

**Comment by xBeastMode** [comment]
Did you compile the plugin on your own? If so, how or where did you compile it?

**Comment by xBeastMode** [comment]
Open issue here: https://github.com/InfinityGamers/HungerGames-UPDATED/issues
